### ISSUE TITLE
[Feature Request] Duplicate server checker

### ISSUE THREAD

**Issue by 265866** [eternal404/nitro-sniper#136]
**Is your feature request related to a problem? Please describe.**
Multiple alts are on the same servers

**Describe the solution you'd like**
On startup:
    Get ids of all servers across all alts
    If duplicates are found, leave the server until only one alt is on that server
On server join:
    See if the guild in the invite link matches with any of the servers on any of the other alts, if it does, don't join

**Comment by Ender786** [comment]
Making the alts leave the servers automatically can result in the alts being banned for selfbot

**Comment by 265866** [comment]
@Ender786 really anything can- just like the invite joiner, I'm sure it'll be safe if you have proper cooldowns and stuff though

**Comment by InimicalPart** [comment]
For this, you would need to use the invite sniper, or else this will basically not happen automatically. As @Ender786 says, this also can get easily detected and get your account banned as the invite sniper is already very easy to detect. Maybe some proper cooldowns will solve this issue, but using the invite sniper will most certainly get your account banned.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by Frog-PG** [comment]
Maybe compare the server id and if any duplicates are found make only 1 alt that's on the duplicate server read the messages, that way you don't have to leave the server

**Comment by eternal404** [comment]
Too resource intensive.
