### ISSUE TITLE
[Feature Request] Abide with giveaway requirements

### ISSUE THREAD

**Issue by Niqutincho** [eternal404/nitro-sniper#192]
**Is your feature request related to a problem? Please describe.**
No, its not. [...]

**Describe the solution you'd like**
I would like it so it reacts to the giveaway, joins the server (REQ) and if u win it auto dms the hoster.

**Additional context**
Nothing more! Good job!

**Comment by NotAtic** [comment]
Yes, this is a really nice idea, i always win giveaways when i'm sleeping and most of them have a "server requirement" Like i have to join the discord server, So i think this will really help.

**Comment by NelsonH75** [comment]
nah, its rare that you get req and if you do they put in the giveaway title so just lacklist works like req.

**Comment by NotAtic** [comment]
Slow are you gonna add this

**Comment by Ender786** [comment]
It is possible to do this but it will most likely get your account terminated, there isn't a safe way at the moment to make accounts join servers without getting them banned.

**Comment by eternal404** [comment]
Not planned, this is mostly a nitro sniper, not a cross-server giveaway sniper.
