### ISSUE TITLE
[Feature Request] Option to customize webhook messages

### ISSUE THREAD

**Issue by Matka150** [eternal404/nitro-sniper#263]
### Is your feature request related to a problem?

My feature isn't related to a problem.

### Describe the solution you'd like

 Like on codeSuccess: Sniped ${nitro-type}, Enjoy your Nitro (${time_taken}ms)!
And for all cases.
Add sort of option for variables like {something} or %something% .

### How will this be beneficial to the sniper

Make the webhook more friendly and customized.
The user can mention specifc role/user.

### Please provide an example of usage of this feature

Maybe on settings:

//custom message on=true off=false. (vars: ${nitro_type}, ${time_taken}, ${author}, ${account}), for mention use <@role/user's id>
codeSuccessCustomMessage: true
codeSuccessCustomMessageContent: "Just got ${nitro_type} for ${account} thanks to ${author} in ${time_taken}ms. Feeling good! <@544674686867> <@45649846464>"

------------------------------------------------------
Mention can be with ID or username and role name. It's up to you

**Comment by eternal404** [comment]
fix above
