### ISSUE TITLE
[Feature Request] Server boost checker

### ISSUE THREAD

**Issue by ghostyplayz** [eternal404/nitro-sniper#303]
### Is your feature request related to a problem?

Invite sniper checks members, but never checks server boosts.

### Describe the solution you'd like

Invite sniper will only join if server has x amount of server boost.

### How will this be beneficial to the sniper

Usually, the more server boost's, the more nitro being dropped and giveaways happening in the server. This should help snipe more active communities.

### Please provide an example of usage of this feature

Invite sniper checks boost's, checks its 10<, if 10< joins server.

**Comment by slow** [comment]
useless, if pull requests it i’ll merge it but im not adding this myself
