### ISSUE TITLE
[Bug] npx command not found

### ISSUE THREAD

**Issue by Betsthebest** [eternal404/nitro-sniper#327]
### Describe the bug

I installed it on replit, did everything like said in the installation guide, and when i try to run it, it says me "npx command not found". Even if i installed nodejs, it's still not working.

### To Reproduce

1. Do the same things than said in Installation.
2. Try to run it.

### Expected behavior

It should have worked.

### Please provide your snipers settings.

```javascript
{
   tokens: {
      // Main Token (ex: Nz...)
      main: '...',
      // Alt Tokens (ex: Nz...)
      alts: [
         '...',
      ],
   },
   // The mode to run the sniper in. Options: main (only main account), alts (only alts), both
   mode: 'both',
   /*
      The status the accounts should be on.
      Options: online, dnd, idle, offline, default
      default means the status will not be modified.
   */
   status: {
      // The status the main account will have IF it's logged in
      main: 'default',
      // The status the logged in alts will have
      alts: 'default'
   },
   nitro: {
      // The amount of nitros needed to be sniped for the cooldown to activate
      max: 3,
      // Cooldown to activate after max nitro has been hit (in hours)
      cooldown: 10,
      dm: {
         /*
          * How long to wait before attempting to claim the nitro in DMs (in seconds)
          * This is to avoid suspicion when winning giveaways by slowing down the sniper from instantly sniping it.
          */
         delay: 10
      }
   },
   giveaway: {
      // Wether or not to activate the giveaway sniper (true/false)
      enabled: true,
      // Delay to react to the giveaway (in seconds)
      delay: 30,
      // DM the hoster on giveaway win (true/false)
      dm: true,
      // Messages to DM the host
      dmMessages: [
         'Hey, i won the giveaway.',
         'Could i redeem my prize?'
      ],
      // How long to wait to DM (in seconds)
      dmDelay: 25,
      // How long to wait between messages (in seconds)
      messageDelay: 2,
      // Blacklisted words for giveaway prizes
      blacklistedWords: [
	 'warn',
         'bot',
         'test',
         'ban'
      ],
      // Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: false,
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro'
      ],
      // Blacklisted Server IDs to not snipe giveaways on
      blacklistedServers: [
         ''
      ],
      // Only snipe giveaways on whitelisted servers (true/false)
      whitelistServersOnly: false,
      whitelistedServers: [
        ''
      ]
   },
   invite: {
      // Wether or not to activate the invite sniper (true/false)
      enabled: true,
      delay: {
         // Minimum delay to join the server (in seconds)
         min: 10,
         // Maximum delay to join the server (in seconds)
         max: 20
      },
      members: {
         // The minimum member count the server should have
         min: 500,
         // The maximum member count the server should have
         max: 50000
      },
      // The amount of joined invites needed for the cooldown to activate
      max: 10,
      // Cooldown to activate after max joined invites has been hit (in hours)
      cooldown: 6,
      // Whether to accept an invite on any other alt/account (depends on "mode") if the current alt has max servers (true/false)
      queue: true,
      // Whether to allow the main token to snipe invites ONLY if sniper mode is set to "both" (true/false)
      onlyAlts: true
   },
   webhook: {
      // URL to fire webhook to for notifications (ex: https://discord.com/api/webhooks/.../...)
      url: '...',
      enabled: {
         // Fire webhook on invalid code (true/false)
         codeInvalid: true,
         // Fire webhook on already redeemed code (true/false)
         codeAlreadyRedeemed: true,
         // Fire webhook on sniped code (true/false)
         codeSuccess: true,
         // Fire webhook on giveaway enter (true/false)
         giveawayEntered: true,
         // Fire webhook on giveaway win (true/false)
         giveawayWin: true,
         // Fire webhook on invite join (true/false)
         inviteJoin: true,
         // Fire webhook on failure of sniping invite (true/false)
         inviteFail: true
      },
      mentionEveryone: {
         // Mention on invalid code (true/false)
         codeInvalid: false,
         // Mention on already redeemed code (true/false)
         codeAlreadyRedeemed: false,
         // Mention on sniped code (true/false)
         codeSuccess: true,
         // Mention on giveaway enter (true/false)
         giveawayEntered: false,
         // Mention on giveaway win (true/false)
         giveawayWin: true,
         // Mention on invite join (true/false)
         inviteJoin: false,
         // Mention on failure of sniping invite (true/false)
         inviteFail: false
      }
   }
}
```

### What platform are you seeing the problem on?

Repl.it

### Relevant log output if applicable.

```text
 bash main.sh
main.sh: line 1: node: command not found
main.sh: line 25: cd: nitro-sniper: No such file or directory
Installing packages, please wait...
Installed dependencies.
Cloning the latest sniper code...
Cloned latest version of the sniper.
Installing sniper dependencies...
Installed sniper dependencies.
Running sniper...
main.sh: line 22: npx: command not found
exit status 127
```

**Comment by rmpitts94** [comment]
i got a little further than that. been working on it for a few hours now. but i keep getting closer. ill keep you up to date. But you need to fill out the info in your settings such as your token and what not.

**Comment by rmpitts94** [comment]
i got it. it is in a backwards ass way but it works.

goto https://replit.com/new
click "Import From Github"
copy this repository link
paste it
click "+ Import From Github", and wait
after that you'll see "select language" on the right side of the project
search for "Bash"
you'll see "configure the run button", enter it with "bash main.sh"
click done
Click shell
type out
 git clone https://github.com/slow/nitro-sniper nitro-sniper
then type
cd nitro-sniper
then
npm install
it will install a bunch of files. it will say there is an update to a program. ignore it dont need it.
Now before we finish up we want to go to the .env file. 
In the left hand column of files you want to click the drop down arrow of nitro-sniper, then click on env. read through it and fill in the blanks and change what you want to your perfered settings. once that is done back in shell type
node .

and youre done!!

**Comment by yxngPlaya** [comment]
> i got it. it is in a backwards ass way but it works.
> 
> goto https://replit.com/new click "Import From Github" copy this repository link paste it click "+ Import From Github", and wait after that you'll see "select language" on the right side of the project search for "Bash" you'll see "configure the run button", enter it with "bash main.sh" click done Click shell type out git clone https://github.com/slow/nitro-sniper nitro-sniper then type cd nitro-sniper then npm install it will install a bunch of files. it will say there is an update to a program. ignore it dont need it. Now before we finish up we want to go to the .env file. In the left hand column of files you want to click the drop down arrow of nitro-sniper, then click on env. read through it and fill in the blanks and change what you want to your perfered settings. once that is done back in shell type node .
> 
> and youre done!!







yes but how do we keep the bot alive, becouse when i use UptimeRobot it works for 10 minutes and it stops working .

**Comment by yungcartionthachair** [comment]
> 

the .env file in nitro-sniper is public. do not paste anything there.

**Comment by minguminx** [comment]
wym by "once that is done back in shell type"

**Comment by yxngPlaya** [comment]
> the .env file in nitro-sniper is public. do not paste anything there, instead, fill out the settings secret environment variable (its already made just fill out the value portion) and run it from the run button rather than "node ."

bro send me your discord please

**Comment by yungcartionthachair** [comment]
this guys guide is all over the place. watch this and follow the steps exactly as shown in the video & in the discord and you wont have any problems.

https://www.youtube.com/watch?v=hYusQ6qeyy4

**Comment by eternal404** [comment]
Fixed, use the new installation method on the wiki.
