### ISSUE TITLE
[Feature Request] variables?

### ISSUE THREAD

**Issue by AvaneeshG** [eternal404/nitro-sniper#342]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I would like to be able to use things like ${prize}(nitro),${server}...etc

### How will this be beneficial to the sniper

Idk maybe tell the host what you won

### Please provide an example of usage of this feature

Won nitro gw --
Dms host --
Ayo I won nitro (${prize})
Claim
(This can be anything this is just my settings)

**Comment by eternal404** [comment]
Not planned.
