### ISSUE TITLE
[Bug] Autoreact not works

### ISSUE THREAD

**Issue by l0g4n1337** [eternal404/nitro-sniper#359]
### Describe the bug

I use these settings but do not automatically participate in giveaways, I have to do it manually.

### To Reproduce

// Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: false,
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro'

### Expected behavior

The reaction to the giveaway should be automatic, but not!

### Please provide your snipers settings.

```javascript
// Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: false,
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro'
```

### What platform are you seeing the problem on?

Repl.it

**Comment by eternal404** [comment]
Duplicate of #152 as it only currently supports the most popular giveaway bot.
