### ISSUE TITLE
[Feature Request] All Giveaway Sniper

### ISSUE THREAD

**Issue by MEZBATHEKING** [eternal404/nitro-sniper#366]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

No it's not a bug or problem. When some giveaway will start it will join any giveaways means all giveaways! It would be better and it should be on a new repository.

### How will this be beneficial to the sniper

It would be benefited by users cause ppls wants join all giveaways. Not only nitro!

### Please provide an example of usage of this feature

Told on description ^^ :)

**Comment by eternal404** [comment]
There are configurable keywords to join and there is also a whitelist only mode.
