### ISSUE TITLE
[Bug] Bug Here

### ISSUE THREAD

**Issue by Fujutreyu** [eternal404/nitro-sniper#367]
### Describe the bug

I had my token but bot says Invalid Settings

### To Reproduce

?

### Expected behavior

Work

### Please provide your snipers settings.

```javascript
ALL + my token
```

### Relevant log output if applicable.

```text
IDK
```

**Comment by Motzumoto** [comment]
How is anyone supposed to fix this issue if you dont tell anyone what the issue is, use common sense next time

**Comment by AvaneeshG** [comment]
what  the fuck is this
